### ISSUE TITLE
Suggestion : connaître le nombre de vies des joueurs pendant la partie

### ISSUE THREAD

**Issue by LilianLem** [syldium/Thimble#4]
Bonjour,
J'essaie actuellement de mettre en place au mieux un dé à coudre sur mon serveur, en regardant les fonctionnalités disponibles sur ce plugin et sur un autre, qui sont tous deux à jour en 1.18.

Je trouve ce plugin meilleur notamment grâce à son intégration avec LuckPerms et le fait de n'avoir aucun item lié au plugin dans son inventaire pendant la partie, mais un scoreboard sur la droite de l'écran serait le bienvenu afin de savoir en permanence combien de vies on possède et combien en ont les autres, pour pouvoir adapter sa stratégie.

Cela serait-il envisageable ?

**Comment by syldium** [comment]
Bonjour,

Il est déjà possible d'afficher un scoreboard lors de la partie et de modifier son contenu dans le fichier `scoreboard.yml`. Ce fichier est à créer manuellement la première fois. Les scoreboards peuvent être différents par arène et le groupe de configuration `default` permet de le définir pour toutes les arènes. Le placeholder `<points>` est remplacé par le nombre de vies du joueur.

Exemple de configuration :
```yml
# plugins/Thimble/scoreboard.yml
default:
  # Nom et contenu du scoreboard
  title: "<blue>Thimble</blue>"
  lines:
    - "Actuel: <dark_green><jumper></dark_green>"
    - "Suivants:"
    - "1. <#d003d0><next_jumper></#d003d0>"
    - "2. <light_purple><next_jumper></light_purple>"
    - ""
    - "Réussis: <gold><jumps></gold>"
    - "Dés à coudre: <gold><thimble></gold>"
    - "<points> <red>❤</red>"
  # Valeurs par défaut à afficher
  empty:
    jumper: "<gray>?</gray>"
    next_jumper: "<gray>?</gray>"
```
